//let fs=require("fs");
//let content=fs.readFileSync("fs.text");
//console.log("content : "+content);
//fs.writeFileSync("fs.text", "Hum aj khus nhi hai");
//fs.appendFileSync("fs.text", "Bhai khus kyo nhi");
//content=fs.readFileSync("fs.text");
//console.log("content : "+content);
//fs.unlinkSync("fs.text");
//content=fs.readFile("fs.text");
//console.log("File recoverd");
let path=require("path");
let inputArr=process.argv.slice(2);
let Filename=inputArr[0];
let content=inputArr[1];
console.log("Filename", fs.text);
console.log("content", content);
let currentpath=process.Filename();
let filepath=path.join(currentpath,"dir",fs.text);
console.log("filepath", filepath);
fs.writeFileSync(filepath,content);
let fs=require("fs");
fs.writeFileSync("read.text", "Hello welcoe in my channel");
